# This is a basic workflow to help you get started with Actions

name: Notify

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notify2:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
          custom-facts: |
            - name: Custom Fact Name 1
              value: Custom Fact Value 1
            - name: Pull Request example
          environment: development
          show-on-failure: true