name: Pull Request Development

on:
  pull_request:
    branches: [ development ]
    types: [opened, synchronize, reopened]

jobs:

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install -f

      - name: Create coverage
        run: npm run test -- --coverage

      - name: Determine test result
        id: test_result
        run: |
          if [ $? -eq 0 ]; then
            echo "::set-output name=test_passed::true"
          else
            echo "::set-output name=test_passed::false"
          fi

  notify_teams:
    runs-on: ubuntu-latest
    needs: run_tests
    if: needs.run_tests.outputs.test_passed == 'false'
    steps:
      - uses: actions/checkout@v2
      - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
          # card-layout-start: compact
          environment: development
          show-on-failure: true   
  
  notify_teams_failed:
    runs-on: ubuntu-latest
    needs: run_tests
    if: needs.run_tests.outputs.test_passed == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
          # card-layout-start: compact
          environment: development
          show-on-failure: true   