name: Pull Request Development

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install -f

      - name: Create coverage
        run: npm run test -- --coverage

      - name: Determine test result
        id: test_result
        run: |
          if [ $? -eq 0 ]; then
            echo "::set-output name=test_passed::true"
          else
            echo "::set-output name=test_passed::false"
          fi

