name: Push Development

on:
  push:
    branches: [development]

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
 
  run_tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore node modules cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create coverage
        run: npm run test --coverage

  eslint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Restore node modules cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run ESLint
      run: npm run lint

  notify_teams:
    needs: [run_tests, eslint]
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v2
      - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
          # card-layout-start: compact
          environment: development
          show-on-failure: true

  notify_teams_failed:
    needs: [run_tests, eslint]
    runs-on: ubuntu-latest
    if: ${{ failure() }}

    steps:
      - uses: actions/checkout@v2

      - name: Set Pull Request Status
        run: |
          PR_NUMBER=$(jq -r .pull_request.number "$GITHUB_EVENT_PATH")
          URL="repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER"
          CONTEXT="Test Status"

          DATA="{\"state\": \"failure\", \"context\": \"$CONTEXT\", \"description\": \"Tests failed\", \"target_url\": \"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}"

          echo "Setting status to failure..."
          curl -s -X POST -H "Authorization: Bearer ${{ github.token }}" -d "$DATA" "https://api.github.com/$URL/statuses/$GITHUB_SHA"

      - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
          card-layout-start: compact
          environment: development
          show-on-failure: true
